### PR TITLE
Feat/twitter interface

### LINKED ISSUE #1: Twitter Interface
Originally posted by @pavlovcik:
```
Post every created bounty to the twitter.com/ubiquitydevpool account so that we and partners can retweet specific bounties of interest.

Create a Twitter interface (probably can recycle a GitHub Action or something) so we can pass a string to a function which will post to our Twitter account.
```

### LINKED ISSUE #12: TEST FOR TWITTER INTERFACE
fastest way i could test if it tweets is making an issue that will get picked up by the script. 

https://twitter.com/0x4007

### PR DESCRIPTION
**Pull request by 0x4007**
Resolves https://github.com/ubiquity/devpool-directory-bounties/issues/1 
Resolves https://github.com/ubiquity/devpool-directory-bounties/issues/12

### CODE REVIEW

**Comment by 0x4007** [comment]
Hey @rndquu would you mind taking over this task? I think the code is fine but I haven't been able to test the keys. The time consuming part right now is figuring out how to authenticate on Twitter (it seems overly complicated with signups etc.)

I set all the keys in the GitHub Actions secrets, but I wanted to confirm a local run before merging. 

I basically just created a new issue right before running the script locally to see if it gets picked up and tweets.

I was hoping to get this up and running for when Taiko starts using it so they can easily retweet and promote us.

**Comment by rndquu** [comment]
> Hey @rndquu would you mind taking over this task? I think the code is fine but I haven't been able to test the keys. The time consuming part right now is figuring out how to authenticate on Twitter (it seems overly complicated with signups etc.)
> 
> I set all the keys in the GitHub Actions secrets, but I wanted to confirm a local run before merging.
> 
> I basically just created a new issue right before running the script locally to see if it gets picked up and tweets.
> 
> I was hoping to get this up and running for when Taiko starts using it so they can easily retweet and promote us.

So this PR should be able to sync all issues from this repo with the ubiquity's twitter account, right?

**Comment by 0x4007** [comment]
Just newly posted ones should be tweeted.

**Comment by rndquu** [comment]
> Just newly posted ones should be tweeted.

Should we delete a tweet if an issue was closed?

**Comment by 0x4007** [comment]
> > Just newly posted ones should be tweeted.
> 
> 
> 
> Should we delete a tweet if an issue was closed?

Let's consider that a separate feature. It's a cool idea!

**Comment by rndquu** [comment]
> > > Just newly posted ones should be tweeted.
> > 
> > 
> > Should we delete a tweet if an issue was closed?
> 
> Let's consider that a separate feature. It's a cool idea!

Ok, I will take over this task

**Review by rndquu — APPROVED** [review]

**Pull request merged**
