### PR TITLE
feat: sync priority and time labels

### LINKED ISSUE #3: Sync priority and time labels
Right now only the `Price` label is synced. We should also sync `Priority` and `Time` labels from partners' issues.

### Edit 31 Aug 

- [x] Please sync all labels, intended to describe the type of task it is (Solidity, UI/UX etc)
- [x] disable `assistive-pricing` on the repo so that the bot doesn't try to price the sync'd priority and time labels.

### PR DESCRIPTION
**Pull request by rndquu**
Resolves https://github.com/ubiquity/devpool-directory-bounties/issues/3

### CODE REVIEW

**Review by 0x4007 — COMMENTED** [review]
Won't this cause an issue with the bot automatically pricing the mirrored bounties? Will you prefix the priority and time labels with some symbol to invalidate them etc?

I am looking at https://github.com/rndquu/devpool-directory/issues/12 but it is not clear to me if you have UbiquiBot added to your fork so it might not be attempting to price it.

**Comment by rndquu** [comment]
> Won't this cause an issue with the bot automatically pricing the mirrored bounties? Will you prefix the priority and time labels with some symbol to invalidate them etc?
> 
> I am looking at https://github.com/rndquu/devpool-directory/issues/12 but it is not clear to me if you have UbiquiBot added to your fork so it might not be attempting to price it.

Yes, the bot messes the labels. Let's wait for https://github.com/ubiquity/ubiquibot/issues/396

**Comment by 0x4007** [comment]
> > Won't this cause an issue with the bot automatically pricing the mirrored bounties? Will you prefix the priority and time labels with some symbol to invalidate them etc?
> > I am looking at https://github.com/rndquu/devpool-directory/issues/12 but it is not clear to me if you have UbiquiBot added to your fork so it might not be attempting to price it.
> 
> Yes, the bot messes the labels. Let's wait for [ubiquity/ubiquibot#396](https://github.com/ubiquity/ubiquibot/issues/396)

We must disable `assistive-pricing` on the local repo config by the way!

**Comment by rndquu** [comment]
> > > Won't this cause an issue with the bot automatically pricing the mirrored bounties? Will you prefix the priority and time labels with some symbol to invalidate them etc?
> > > I am looking at https://github.com/rndquu/devpool-directory/issues/12 but it is not clear to me if you have UbiquiBot added to your fork so it might not be attempting to price it.
> > 
> > 
> > Yes, the bot messes the labels. Let's wait for [ubiquity/ubiquibot#396](https://github.com/ubiquity/ubiquibot/issues/396)
> 
> We must disable `assistive-pricing` on the local repo config by the way!

[done](https://github.com/ubiquity/devpool-directory/blob/development/.github/ubiquibot-config.yml#L1)

**Comment by rndquu** [comment]
Closing this in favor of a new PR

**Pull request closed without merging**
