### PR TITLE
fix: fix reopening issues

### LINKED ISSUE #22: Bug: fix reopening issues
Check this [issue](https://github.com/ubiquity/devpool-directory/issues/984#event-12112923776). You may see that it is constantly opened and closed on every [sync workflow](https://github.com/ubiquity/devpool-directory/blob/development/.github/workflows/sync-issues.yml) run.

What should be done:
- find the root cause of why the issue is reopened
- fix the bug

### PR DESCRIPTION
**Pull request by rndquu**
Resolves https://github.com/ubiquity/devpool-directory-bounties/issues/22

### CODE REVIEW

**Comment by gentlementlegen** [comment]
I am a bit skeptical about this fix, it seems to be following the exact same logic except that the `if` is nested instead of being in the condition? All the change I see is a`console.log` saying the issue is already closed.

**Comment by rndquu** [comment]
> I am a bit skeptical about this fix, it seems to be following the exact same logic except that the `if` is nested instead of being in the condition? All the change I see is a`console.log` saying the issue is already closed.

There is a change, this PR closes issues assigned in partner projects no matter what, while previously we closed them only if certain conditions are met

**Comment by 0x4007** [comment]
Why don't you run this off of your fork and we can compare the results.

**Comment by EresDev** [comment]
> I am a bit skeptical about this fix, it seems to be following the exact same logic except that the if is nested instead of being in the condition? All the change I see is aconsole.log saying the issue is already closed.

I agree with this. 

> There is a change, this PR closes issues assigned in partner projects no matter what, while previously we closed them only if certain conditions are met

I couldn't find a difference in conditions to close the issue by this code, and the previous one before change.

**Comment by rndquu** [comment]
> Why don't you run this off of your fork and we can compare the results.

I've already run it against my fork

> I couldn't find a difference in conditions to close the issue by this code, and the previous one before change.

One more time, there is a difference, now if partner issue is [assigned](https://github.com/ubiquity/devpool-directory/pull/1158/files#diff-dcdc3e0b3362edb8fec2a51d3fa51f8fb8af8f70247e06d9887fa934834c9122R101) then we [don't do anything](https://github.com/ubiquity/devpool-directory/pull/1158/files#diff-dcdc3e0b3362edb8fec2a51d3fa51f8fb8af8f70247e06d9887fa934834c9122R113) with it, while the previous code version continued to [this](https://github.com/ubiquity/devpool-directory/blob/0d83381833e9a28b04ed31ee0242e0012091491b/index.ts#L150) update in case partner issue was assigned and devpool issue was closed

Overall I wonder why anybody doesn't just run this PR to check how it works

**Review by EresDev — APPROVED** [review]
Ok, I found the difference. It is when the `continue;` is called. 

The change calls `continue;` at a different condition, and stops more conditions below to run and manipulate the closed issue. 

Because if the `continue;` is not called here, one of the next blocks is responsible for reopening a closed issue. 

https://github.com/ubiquity/devpool-directory/blob/0d83381833e9a28b04ed31ee0242e0012091491b/index.ts#L142

**Comment by 0x4007** [comment]
I mean you should run [sync-issues](https://github.com/rndquu/devpool-directory/actions/workflows/sync-issues.yml) and we should see the final results on your issues. I think this should be standard for everybody working on this now that we don't have the "link back" problem anymore. 

This also clearly shows what we can expect to see instead of merging in and finding some bug. I can't afford that since we're presenting the work.ubq.fi interface all week.

**Comment by gentlementlegen** [comment]
I was not with a computer available and tried to give a review when I could because I thought it was an important fix. The preview of the change was misleading and thank you @EresDev for pointing the change out, my bad.

**Review by gentlementlegen — APPROVED** [review]

**Comment by rndquu** [comment]
I ran this PR 2 times against https://github.com/ubiquity/devpool-directory and issues were not reopened:
- https://github.com/ubiquity/devpool-directory/actions/runs/8465393815
- https://github.com/ubiquity/devpool-directory/actions/runs/8465442219

**Pull request merged**
