### PR TITLE
fix: run code on push to dev only

### LINKED ISSUE #10: Unexpected Repository Included
This isn't inside of the `projects.json` list so I'm not sure how it got in the directory.

- https://github.com/ubiquity/devpool-directory/issues/734

This should be diagnosed and fixed.

### PR DESCRIPTION
**Pull request by devpanther**
Resolves https://github.com/ubiquity/devpool-directory-bounties/issues/10

### CODE REVIEW

**Comment by devpanther** [comment]
@rndquu This works?

**Comment by rndquu** [comment]
> @rndquu This works?

Did you try it for you forked repo?

Pls also keep the `workflow_dispatch` event, it is useful for debugging

The sync workflow should not run if PR is closed, only on pushes to the `development` branch

**Comment by devpanther** [comment]
Screenshot 2023-07-30 at 10 32 15 PM

@rndquu it works, after several tests. I got it running on my repo and this is the result

PR 8: https://github.com/devpanther/devpool-directory/pull/8 - A push to random branch, sync issues wasn't triggered
PR 9: https://github.com/devpanther/devpool-directory/pull/9 - A successful push to `development` branch and sync issues was triggered
PR 10: https://github.com/devpanther/devpool-directory/pull/10 - A PR attempt to `development` that was closed, no sync issues was triggered

It failed because I don't have the secrets setup btw

**Review by rndquu — APPROVED** [review]

**Comment by devpanther** [comment]
Follow up here @pavlovcik

**Review by 0x4007 — APPROVED** [review]

**Pull request merged**
