### PR TITLE
fix: delete unauthorized issues

### LINKED ISSUE #31: Delete issues created by contributors
Original [comment](https://github.com/ubiquity/devpool-directory-bounties/issues/30#issuecomment-2292647684)

Right now anybody can create a new github issue in https://github.com/ubiquity/devpool-directory and it will be displayed at `work.ubq.fi`:
Screenshot 2024-08-19 at 16 09 32

Allowing anybody to create issues in https://github.com/ubiquity/devpool-directory is not optimal because:
- anybody can flood `work.ubq.fi` with issues (illustrated on the screenshot above)
- anybody can create a github issue with phishing URLs and that github issue will be displayed directly at `work.ubq.fi`

One of the solutions could be to remove issues from https://github.com/ubiquity/devpool-directory if they're opened not by one of the following bots (id => github URL):
1. `76412717: https://github.com/ubiquity`
2. `133917611: https://github.com/ubiquibot`
3. `165700353: https://github.com/UbiquityOS`

P.S. There is also the [limit interaction](https://docs.github.com/en/communities/moderating-comments-and-conversations/limiting-interactions-in-your-repository#about-temporary-interaction-limits) option but if we enable it then new contributors won't be able to open PRs towards https://github.com/ubiquity/devpool-directory

### PR DESCRIPTION
**Pull request by Keyrxng**
Resolves https://github.com/ubiquity/devpool-directory-bounties/issues/31

I QA'd the script manually locally and it works as expected. When using my PAT (with admin rights) issues are deleted. When using a different PAT it failed to remove any. Without the official instance env vars this was as close as I could get to fully testing it locally but I expect no issues.

- All issues created by my bot and `Keyrxng` were kept and any by my alt `Keyrxng2` were deleted.

- `GH_TOKEN` needs to be defined in secrets for this script to have the correct permissions.

- We authenticate as the `App` using the `APP_PRIVATE_KEY` and `APP_ID` so we can pull the installs. 
- We then map those to cover `User` and `Bot` types. If it's a bot we need to map the username to the `appSlug` as it's `userId` does not correspond to the `orgId` which it belongs to.
- For user's we map the `userId` directly.

While it's usually best to use numbers vs strings for identification this works just fine for identifying Bots as far as I could QA and was the best option I could think of given what was available.

---

In regards to future contributions we have two options:

1. Leave it as-is and forks need to define the correct secrets for this functionality to work
2. Don't throw for missing vars and without env vars we can assume this feature is disabled

### CODE REVIEW

**Review by 0x4007 — APPROVED** [review]

**Comment by Keyrxng** [comment]
[I see it failed](https://github.com/ubiquity/devpool-directory/actions/runs/10548262923/job/29221949842), I thought it would have access to the global `APP_ID` secret. I'll need to place those into the `env` of that step

**Comment by Keyrxng** [comment]
QA: https://github.com/ubiquity/devpool-directory/actions/runs/10548454915/job/29222385653#step:8:11

The `GH_TOKEN` secret needs set and it should work

image

**Comment by rndquu** [comment]
@Keyrxng I've just QAed with an issue created by a user (by me actually) and the issue was deleted as expected https://github.com/ubiquity/devpool-directory/issues/1374.

Right now [GH_TOKEN](https://github.com/ubiquity/devpool-directory/blob/61045f468246a6fdde9901a400f0f9c1b348272f/.github/workflows/sync-issues.yml#L54) end variable is set to `0x4007`'s  PAT.  Do we keep using this PAT or we should create a separate github app with admin access to the https://github.com/ubiquity/devpool-directory repository solely for deleting issues?

**Comment by rndquu** [comment]
The solution with deleting unauthorized issues on "sync" still has a window for phishing since the sync workflow runs [once an hour](https://github.com/ubiquity/devpool-directory/blob/61045f468246a6fdde9901a400f0f9c1b348272f/.github/workflows/sync-issues.yml#L12) so an issue created by an adversary will be visible for a whole hour at `work.ubq.fi` in the worst case.

**Comment by Keyrxng** [comment]
I'm not 100% but I'm sure that in order to have an app be able to delete issues we'd need to make it a member of the org and/or be able to assign it an `admin` role. 

I think just sticking to a fine-grained PAT with permissions only for `devpool-directory` is sufficient because no one is ever going to see who or what deleted the issue it'll just be deleted. In the end the two tokens should have the same permissions and restrictions anyway so I don't think it's needed personally.

**Comment by Keyrxng** [comment]
> The solution with deleting unauthorized issues on "sync" still has a window for phishing since the sync workflow runs [once an hour](https://github.com/ubiquity/devpool-directory/blob/61045f468246a6fdde9901a400f0f9c1b348272f/.github/workflows/sync-issues.yml#L12) so an issue created by an adversary will be visible for a whole hour at `work.ubq.fi` in the worst case.

The hacky quick-fix that I PR'd against `work.ubq.fi` would solve this I guess

**Comment by rndquu** [comment]
> I'm not 100% but I'm sure that in order to have an app be able to delete issues we'd need to make it a member of the org and/or be able to assign it an `admin` role.
> 
> I think just sticking to a fine-grained PAT with permissions only for `devpool-directory` is sufficient because no one is ever going to see who or what deleted the issue it'll just be deleted. In the end the two tokens should have the same permissions and restrictions anyway so I don't think it's needed personally.

@0x4007 Are you ok with the approach that your github PAT is used for deleting issues?

**Comment by rndquu** [comment]
> > The solution with deleting unauthorized issues on "sync" still has a window for phishing since the sync workflow runs [once an hour](https://github.com/ubiquity/devpool-directory/blob/61045f468246a6fdde9901a400f0f9c1b348272f/.github/workflows/sync-issues.yml#L12) so an issue created by an adversary will be visible for a whole hour at `work.ubq.fi` in the worst case.
> 
> The hacky quick-fix that I PR'd against `work.ubq.fi` would solve this I guess

What PR do you mean?

**Comment by Keyrxng** [comment]
@rndquu 

- https://github.com/ubiquity/work.ubq.fi/pull/81

**Comment by rndquu** [comment]
> @rndquu
> 
> * [fix: paginate issues work.ubq.fi#81](https://github.com/ubiquity/work.ubq.fi/pull/81)

It its current view it doesn't solve the phishing issue

**Comment by Keyrxng** [comment]
> > @rndquu
> > 
> > * [fix: paginate issues work.ubq.fi#81](https://github.com/ubiquity/work.ubq.fi/pull/81)
> 
> It its current view it doesn't solve the phishing issue

Correct the review comments lead us to it's current state. I can open an issue and implement either a more robust check or re-implement the naive version I had originally. 

https://github.com/ubiquity/work.ubq.fi/pull/81#discussion_r1721859134

**Comment by rndquu** [comment]
@Keyrxng What if we run [delete-unauthorized-issues.ts](https://github.com/ubiquity/devpool-directory/blob/61045f468246a6fdde9901a400f0f9c1b348272f/scripts/delete-unauthorized-issues.ts) in a separate workflow on `issues.opened`?

**Comment by Keyrxng** [comment]
That would do it but it wouldn't be super clean as it would fire on every new issue and after the 1hr period we may have multiple new issues opened.

Not a deal breaker though that would work

**Comment by rndquu** [comment]
> after the 1hr period we may have multiple new issues opened

Why is that an issue?

**Comment by rndquu** [comment]
> That would do it but it wouldn't be super clean as it would fire on every new issue and after the 1hr period we may have multiple new issues opened.
> 
> Not a deal breaker though that would work

https://github.com/ubiquity/devpool-directory-bounties/issues/35

**Comment by 0x4007** [comment]
> @0x4007 Are you ok with the approach that your github PAT is used for deleting issues?

I think its more professional to use a dedicated app for this. Besides, I'm pretty sure it counts towards my contribution history on my profile, which would not be genuine. 

I can make the app in a bit.

**Comment by 0x4007** [comment]
Screenshot 2024-08-26 at 23 48 55

@Keyrxng I am deleting `GH_TOKEN`. Please use these to authenticate as the new app.

**Comment by Keyrxng** [comment]
> Screenshot 2024-08-26 at 23 48 55
> @Keyrxng I am deleting `GH_TOKEN`. Please use these to authenticate as the new app.

I believe that `GH_TOKEN` is a requirement of using the CLI within a workflow env. 

> QA: https://github.com/ubiquity/devpool-directory/actions/runs/10548454915/job/29222385653#step:8:11
> 
> The `GH_TOKEN` secret needs set and it should work
> 
> image


---

So I think my approach will be to obtain the auth token from the new app and pass that to our delete step as `GH_TOKEN` and it should work if it's possible to use the app.

Struggling to think how I can QA this without also creating a new app myself but I will see what it takes and open a PR

**Comment by 0x4007** [comment]
Just merge and test in prod it's fine.

**Comment by Keyrxng** [comment]
> Just merge and test in prod it's fine.

I was sweating testing this in prod considering how destructive `delete` is. All I kept thinking was:

If somehow all of the closed issues got deleted, they wouldn't be backfilled would they? We'd need to write a script to do it?

But sure I can do that 😂

**Comment by 0x4007** [comment]
I'm pretty sure they will be automatically repopulated every time the script runs.

**Comment by rndquu** [comment]
I've just tried to use the bot's access token to delete [this](https://github.com/ubiquity/devpool-directory/issues/1377) issue and got the `GraphQL: Viewer not authorized to delete (deleteIssue)` error in [this](https://github.com/ubiquity/devpool-directory/actions/runs/10599106506/job/29373303161) CI run.

As [stated](https://docs.github.com/en/issues/tracking-your-work-with-issues/deleting-an-issue) in the docs `Only accounts with admin or owner permissions can delete issues in a repository owned by an organization`. So although the `ubiquity-os` has read/write permissions for issues it can't delete them.

So we have 2 choices:
1. Use someone's PAT to delete issues
2. Simply close unauthorized issues by the bot

**Comment by 0x4007** [comment]
2. Will negatively affect statistics on ubq.fi

Maybe I can look for some type of admin permissions for the dedicated app. Otherwise yes, PAT.

Just verified that [there is no endpoint](https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps#repository-permissions-for-issues) for deleting issues. So I can set up a dedicated account with the PAT then.

**Comment by 0x4007** [comment]
Just re-added `GH_TOKEN` hope that somebody can fix this script.

**Comment by Keyrxng** [comment]
> Just re-added `GH_TOKEN` hope that somebody can fix this script.

With this returned it should be okay afaik

**Comment by Keyrxng** [comment]
`GraphQL: Resource not accessible by personal access token (deleteIssue)`

https://github.com/ubiquity/devpool-directory/actions/runs/10599742418

The permissions are not defined properly this time @0x4007

**Comment by 0x4007** [comment]
I asked ChatGPT but I'm not sure. Let me go higher then.

**Comment by 0x4007** [comment]
I am now using a classic token with full repo permissions.

**Comment by 0x4007** [comment]
I think that the logic must have been changed because my permissions have been set to admin. Please review the code @Keyrxng

**Comment by Keyrxng** [comment]
The logic is unchanged

I'm sure the last one was fine-grained, scoped only to the devpool with the resource owner being yourself it should automatically carry admin privileges but I'm sure that `Issue` was selected

> Scope it only to the devpool-directory repo with access to issues and admin on repo settings and idk if needed but admin on org too. 

Is it possible to make a bot/app a member of the org? If that's possible then we should be able to apply an admin role to that org member. I'm just not sure if you can add a bot as a member.

**Comment by 0x4007** [comment]
I see. The account is an admin of the repo, not the org. Seems a bit dangerous. 

If it's the only option I'll look into it later.

**Comment by 0x4007** [comment]
Looks like the logic isn't correct. It deleted basically everything. 

https://github.com/ubiquity/devpool-directory/actions/runs/10599742418/job/29401088016#step:8:11

---

I ran it again and I think its fine now.  

https://github.com/ubiquity/devpool-directory/actions/runs/10608034464/job/29401475685

**Comment by 0x4007** [comment]
Can't write the statistics to the repository. I have contents read & write @Keyrxng do you know?

https://github.com/ubiquity/devpool-directory/actions/runs/10608034464/job/29401761616#step:7:217

**Comment by 0x4007** [comment]
I fixed the permissions problem for committing the statistics to the repository just now. We are using another dedicated app for higher rate limits.

**Comment by Keyrxng** [comment]
`devpool-directory-superintendent`

badass

**Comment by rndquu** [comment]
To sum up, as far as I understand, we have 2 account instances for managing https://github.com/ubiquity/devpool-directory:
1. https://github.com/ubiquity-devpool: github account with the "owner" role [used](https://github.com/ubiquity/devpool-directory/blob/32f312e2b72fd15b447ab13264b85f3a0f1c342e/.github/workflows/sync-issues.yml#L54) for deleting unauthorized github issues
2. https://github.com/apps/devpool-directory-superintendent: github app [used](https://github.com/ubiquity/devpool-directory/blob/32f312e2b72fd15b447ab13264b85f3a0f1c342e/.github/workflows/sync-issues.yml#L44) for opening and closing github issues

**Comment by 0x4007** [comment]
> To sum up, as far as I understand, we have 2 account instances for managing https://github.com/ubiquity/devpool-directory:
> 
> 1. https://github.com/ubiquity-devpool: github account with the "owner" role [used](https://github.com/ubiquity/devpool-directory/blob/32f312e2b72fd15b447ab13264b85f3a0f1c342e/.github/workflows/sync-issues.yml#L54) for deleting unauthorized github issues
> 2. https://github.com/apps/devpool-directory-superintendent: github app [used](https://github.com/ubiquity/devpool-directory/blob/32f312e2b72fd15b447ab13264b85f3a0f1c342e/.github/workflows/sync-issues.yml#L44) for opening and closing github issues

Yes that is correct. I only did it this way because using a personal account seems like a hack, and I tried to minimize the dependency of this for our system.

**Pull request merged**
